# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5168b5549a60ec2ec3cc9d95e198972041f776a92adceba10ec8b63fb622d83442ee7f05167fc50bf23daa7ff09a6d5a430a60e5b7e5bfcc81deb68f3deaeb83

test:
  secret_key_base: 84b2ee86d6c77974de09266ba4dfbb2ccdce38417583e139eb6104832e9b684ccf44d1dd47f8436eb1f965c7750d57913c374308fc216d45fc97d121014379e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
